### ISSUE TITLE
Issue with INSPIRE Validator in dev environment

### ISSUE THREAD

**Issue by kalxas** [EOFarm/geoportal.ypen.gr#11]
We are receiving this error when testing datasets:
```
Test Run initialization failure
Access to the private subnet was rejected by a configuration setting!
```

**Comment by kalxas** [comment]
Enabled the setting `etf.testobject.allow.privatenet.access` as mentioned in the above ticket.

**Comment by grigoriouelena** [comment]
The validator is working properly when testing capabilities.
The issue may close.

**Comment by grigoriouelena** [comment]
It seems that we have not worked with the validator enough to highlight possible issues.

One of them is the following:

When trying to validate a wms with our national validator instance, I see that only the Getcapabilities_operation is tested. 

When I am checking the same resource with the staging instance of the JRC validator (here http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html), I see that more tests are executed (eg GetMao_Operation, Language_requirements).

Furthermore, one of the messages returned by the national instance points to a localhost url.

Reproduction of the issue:
tested resource: http://beta.geoportal.ypen.gr/geoserver/aqd-wms/ows?service=WMS&version=1.3.0&request=GetCapabilities
national validator instance: http://beta.geoportal.ypen.gr/validator
JRC staging validator instance: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html
selected test: WMS

Note! The staging instance of the JRC validator was used because the production instance is not working today November 26th.

I propose to reopen the issue and collect possible fixes requests here.

**Comment by kalxas** [comment]
New version of validator:

https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2022.0

**Comment by kalxas** [comment]
docker.pkg.github.com/inspire-mif/helpdesk-validator/inspire-validator:2022.0 is not yet available

**Comment by kalxas** [comment]
https://github.com/INSPIRE-MIF/helpdesk-validator/issues/707

**Comment by kalxas** [comment]
Fixed upstream
