### ISSUE TITLE
WFS output format

### ISSUE THREAD

**Issue by kalxas** [EOFarm/geoportal.ypen.gr#16]
WFS output from GeoNetwork fails:

![image](https://user-images.githubusercontent.com/383944/140911424-cb43d204-574f-4a4a-a125-c2f81210d23c.png)

![image](https://user-images.githubusercontent.com/383944/140912191-90bc98d4-2473-4bfb-b8ae-977cc3eeb93d.png)

**Comment by grigoriouelena** [comment]
When a gml feature type is requested using the GUI, geonetwork is sending a wfs 1.1.0 request to the  wfs. 

If the service access point, instead of the end point, is used in the /gmd:MD_Metadata/gmd:distributionInfo/gmd:MD_Distribution/gmd:transferOptions/gmd:MD_DigitalTransferOptions/gmd:onLine/gmd:CI_OnlineResource/gmd:linkage/gmd:URL metadata element, for example http://beta.geoportal.ypen.gr/geoserver/amaqd/wfs without the version and request parameters, geonetwork forms the wfs1.1.0 request and the wfs responds with the gml.

The metadata records were edited according to the above.

The issue can be closed.
